/*
 * Sanity test: C++ compute_fp64 must match Python compute_fp64.
 *
 * Reference oracle value (from earlier deck Redis inspection):
 *   scalar 1,415,719,084 -> fp 0x00f1bd44a1a66104
 *
 * If this test passes, the FP64 algorithm is byte-exact compatible with
 * the existing 1.96B-entry deck oracle and the magic_wand_sieve.py
 * tooling. If it fails, we have a parity / endianness / P_HALF / step-
 * direction bug.
 */

#include "fp64.h"
#include <cstdio>
#include <cstdint>

int main() {
    Secp256K1 secp;
    secp.Init();

    /* Reference vector from deck Redis. */
    struct {
        uint64_t k;
        uint64_t expected;
    } cases[] = {
        {1415719084ULL, 0x00f1bd44a1a66104ULL},
        /* k=1, just a smoke value to be regenerated by Python if needed. */
    };

    int fails = 0;
    for (auto &c : cases) {
        uint64_t got = magicwand::compute_fp64(&secp, c.k);
        printf("k=%llu got=0x%016llx expected=0x%016llx %s\n",
               (unsigned long long)c.k,
               (unsigned long long)got,
               (unsigned long long)c.expected,
               (got == c.expected) ? "OK" : "FAIL");
        if (got != c.expected) fails++;
    }

    /* Also smoke-test the from_point path is consistent with the
     * scalar path. */
    Int k_int((uint64_t)42);
    Point Q42 = secp.ComputePublicKey(&k_int);
    uint64_t fp_scalar = magicwand::compute_fp64(&secp, 42);
    uint64_t fp_point  = magicwand::compute_fp64_from_point(&secp, Q42);
    printf("k=42 fp_scalar=0x%016llx fp_point=0x%016llx %s\n",
           (unsigned long long)fp_scalar, (unsigned long long)fp_point,
           (fp_scalar == fp_point) ? "OK" : "FAIL");
    if (fp_scalar != fp_point) fails++;

    return fails == 0 ? 0 : 1;
}
